-- Native loading and emitter lifecycle; deliberately no graphics/device calls.
local env=luanet.import_type('System.Environment')
local gfx=luanet.import_type('RogueEssence.Content.GraphicsManager')
local dm=luanet.import_type('RogueEssence.Data.DataManager')
local layer=luanet.import_type('RogueEssence.Content.DrawLayer')
local sceneType=luanet.import_type('RogueEssence.TitleScene')
local tick=luanet.import_type('RogueEssence.FrameTick')
local output=assert(io.open('cliffnw_night_test.tsv','w'))
local function check(label,value)
 assert(value,label);output:write(label..'\tPASS\n');output:flush()
end
local ok,err=pcall(function()
 gfx.DungeonTexSize=3
 local m=dm.Instance:GetGround('cliffnordouesttest1')
 check('Ground deserializes',m~=nil)
 check('Grid and tile scale retained',m.Width==138 and m.Height==98 and m.TexSize==1)
 check('Four original tile layers',m.Layers.Count==4)
 check('Original decoration/entity layer counts',m.Decorations.Count==1 and m.Entities.Count==1)
 check('Single night status, no daytime duplicate',m.Status.Count==1)
 local s=m.Status['cliffnw_night_overlay']
 check('Hidden visual-only status',s.Hidden and s.StatusStates.Count==0)
 check('Native ordered MultiSwitchEmitter',s.Emitter:GetType().Name=='MultiSwitchEmitter' and s.Emitter.Emitters.Count==2)
 local veil=s.Emitter.Emitters[0];local clouds=s.Emitter.Emitters[1]
 check('First child is native night veil',veil:GetType().Name=='OverlayEmitter' and veil.Anim.AnimIndex=='CLIFFNW_NIGHT_VEIL')
 check('Night opacity176 and stationary',veil.Anim.Alpha==176 and veil.Movement.X==0 and veil.Movement.Y==0)
 check('Second child is native night clouds',clouds:GetType().Name=='OverlayEmitter' and clouds.Anim.AnimIndex=='CLIFFNW_NIGHT_CLOUDS')
 check('Cloud speed minus4px per second',clouds.Movement.X==-4 and clouds.Movement.Y==0)
 check('Both overlays above tile layers',veil.Layer==layer.Top and clouds.Layer==layer.Top)
 local data=dm.Instance:GetMapStatus('cliffnw_night_overlay')
 check('Visual MapStatusData loads',data~=nil and data.DefaultHidden and not data.CarryOver)
 check('No gameplay states or refresh events',data.StatusStates.Count==0 and data.OnMapRefresh.Count==0)
 check('Resource matches the two ordered emitters',data.Emitter.Emitters.Count==2 and data.Emitter.Emitters[0].Anim.AnimIndex==veil.Anim.AnimIndex and data.Emitter.Emitters[1].Anim.AnimIndex==clouds.Anim.AnimIndex)
 -- TitleScene constructor initializes BaseScene animation lists without a GPU.
 -- Never call Begin/Draw; this is only a native emitter test harness.
 local scene=sceneType(false);local emitter=s.Emitter:Clone()
 emitter:Update(scene,tick.Zero)
 check('Creates exactly two native Top animations',scene.Anims[4].Count==2)
 check('Veil spawns before moving clouds',scene.Anims[4][0].Movement.X==0 and scene.Anims[4][1].Movement.X==-4)
 check('Both animations have indefinite lifetimes',scene.Anims[4][0].TotalTime==-1 and scene.Anims[4][1].TotalTime==-1)
 emitter:Update(scene,tick.Zero)
 check('Further updates do not duplicate overlays',scene.Anims[4].Count==2)
 scene.Anims[4][1]:Update(scene,tick.FromFrames(60))
 check('Native cloud clock advances one second',scene.Anims[4][1].Time:ToFrames()==60)
 emitter:SwitchOff()
 check('Both child emitters stop with their parent',emitter.Finished and emitter.Emitters[0].Finished and emitter.Emitters[1].Finished)
end)
if not ok then output:write('FAIL\t'..tostring(err)..'\n') end
output:close();print('CLIFFNW_NIGHT_NATIVE '..(ok and 'PASS' or tostring(err)))
env.Exit(ok and 0 or 1)
